# Use an official Maven image as a base image
FROM maven:3.8.4-openjdk-11

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the project files into the container
COPY . .

# Build the Maven project
RUN mvn clean install

# Set the entry point to run your application
CMD ["java", "-jar", "target/E-Telihealth-0.0.1-SNAPSHOT.jar"]
